language: python
python:
 - "2.7"
 - "3.4"
 - "pypy-5.4.1"
matrix:
  include:
  - os: osx
    language: generic
    env: USE_OPENMP=true BREW_PYTHON3=true
  - os: osx
    language: generic
    env: MB_PYTHON_VERSION=2.7.13
  - os: osx
    language: generic
    env: MB_PYTHON_VERSION=3.4.4
  - os: osx
    language: generic
    env: PYPY_VERSION=5.4.1
  - os: osx
    language: generic
    env: PYPY_VERSION=5.6.0
  - os: osx
    language: generic
    env: PYPY_VERSION=5.7.1
  - os: osx
    language: generic
    env: PYPY_VERSION=5.8.0

  fast_finish: true

sudo: required
dist: trusty
cache: pip

addons:
  apt:
    packages:
      - libsdl2-dev
      - mesa-common-dev

before_install:
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "osx" && "$USE_OPENMP" == "true" ]]; then source .travis/install_openmp.sh; fi'
- 'if [[ "$BREW_PYTHON3" == "true" ]]; then brew install python3; fi'
- 'if [[ "$BREW_PYTHON3" == "true" ]]; then virtualenv venv -p python3; fi'
- 'if [[ "$BREW_PYTHON3" == "true" ]]; then source venv/bin/activate; fi'
- source .travis/install_python.sh
- pip install --upgrade pip setuptools
- 'pip install -U hg+https://bitbucket.org/HexDecimal/wheel@abi3-windows-fix#egg=wheel'
- 'if [[ "$TRAVIS_PYTHON_VERSION" == pypy* || -n "$PYPY_VERSION" ]]; then pip install git+https://bitbucket.org/pypy/numpy.git; fi'
- pip install --requirement requirements.txt
install:
- if [[ -z "$TRAVIS_TAG" ]]; then export BUILD_FLAGS="-g"; fi
- python setup.py build $BUILD_FLAGS develop bdist_wheel
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python -m pip install git+git://github.com/HexDecimal/delocate.git@custom; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then delocate-wheel -v dist/*.whl; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then delocate-listdeps --all dist/*.whl; fi'
before_script:
 - pip install pytest pytest-cov
script:
- pytest -v
after_success:
- pip install codacy-coverage python-coveralls codecov
- if [[ -n "$TRAVIS_TAG" ]]; then pip install twine; fi
- if [[ -n "$TRAVIS_TAG" && "$TRAVIS_OS_NAME" == "osx" ]]; then twine upload --skip-existing dist/*; fi
